name: Node.js Package

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      - name: Set up Nodejs Runtime
        uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: 'npm'
      - name: Install Project Dependencies
        run: npm ci
      - name: Execute tests
        run: npm test